/**
 * Aweborn Card Back: static template (identical on every card ever printed).
 * Exported as a function so colour variants can be rendered for comparison.
 * The chosen values live in BACK_DEFAULTS.
 */
import { outline } from "./outline.mjs";
import { assertSelfContained, contrast } from "./front.mjs";

export const MARK = ["#5b8cb8", "#a480b8", "#e8c860"]; // large r55, medium r34, small r21 (= public/favicon.svg)

export const BACK_DEFAULTS = {
  ink: "#a9c1da", // wordmark: steel blue (final 2026-10-04; was lavender #c9b7d6), 8.4:1 worst case
  frame: "#3a4064",
  ring: "#2a2f50",
  bgInner: "#232327",
  bgOuter: "#141416",
};

/** Lowest wordmark contrast across the vignette (inner stop is the lightest background). */
export const wordmarkContrast = (o = {}) => {
  const p = { ...BACK_DEFAULTS, ...o };
  return Math.min(contrast(p.ink, p.bgInner), contrast(p.ink, p.bgOuter));
};

export function renderBack(o = {}) {
  const p = { ...BACK_DEFAULTS, ...o };
  const wc = wordmarkContrast(p);
  if (wc < 7) throw new Error(`Back wordmark ${p.ink} below WCAG AAA: ${wc.toFixed(2)}:1`);
  const wordmark = outline("aweborn", {
    font: "jost", wght: 400, fitWidth: 24, tracking: 0.12, x: 34.5, y: 77, anchor: "middle", fill: p.ink,
  }).svg;

  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="69mm" height="94mm" viewBox="0 0 69 94">
  <!--
    Aweborn Card Back — static, identical on every card ever printed
    ═════════════════════════════════════════════════════════════════
    GENERATED by scripts/cards/build-back.mjs (template: scripts/cards/lib/back.mjs). Edit those, not this file.

    Format : TCG 63 × 88 mm trim, 3 mm bleed on every side (canvas 69 × 94 mm)
    Units  : 1 user unit = 1 mm
    Trim   : x 3–66, y 3–91 (corner radius ≈ 3 mm, applied by the die cut)
    Safe   : x 6–63, y 6–88 (keep all content inside)
    Mark   : aweborn-logo.svg geometry (r = 21 / 34 / 55, consecutive Fibonacci radii)
             in the favicon palette (f1): steel blue / lilac / gold
    Type   : "aweborn" in Jost 400 (SIL OFL), already outlined — no fonts needed to print

    PRINT NOTE: the frame sits 3.5 mm inside the trim, so off-center cuts will be
    visible. Confirm the vendor's cutting tolerance (ideally ≤ 0.5 mm).
  -->
  <defs>
    <radialGradient id="vignette" cx="50%" cy="46%" r="70%">
      <stop offset="0%" stop-color="${p.bgInner}"/>
      <stop offset="100%" stop-color="${p.bgOuter}"/>
    </radialGradient>
  </defs>

  <!-- Full-bleed background -->
  <rect width="69" height="94" fill="url(#vignette)"/>

  <!-- Hairline frame (inside safe zone) -->
  <rect x="6.5" y="6.5" width="56" height="81" rx="2" fill="none" stroke="${p.frame}" stroke-width="0.2"/>

  <!-- Orbit ring: radius 89 = F₁₁ (the largest tangent distance), scaled with the mark -->
  <circle cx="34.5" cy="43" r="23.5" fill="none" stroke="${p.ring}" stroke-width="0.15"/>

  <!-- Logo mark, centered on (34.5, 43), ~42 mm wide -->
  <g transform="translate(34.5 43) scale(0.264) translate(-201.5 -198)">
    <circle cx="177" cy="198" r="55" fill="${MARK[0]}"/>
    <circle cx="247" cy="217" r="34" fill="${MARK[1]}"/>
    <circle cx="234" cy="173" r="21" fill="${MARK[2]}"/>
  </g>

  <!-- Wordmark: "aweborn", Jost 400, 24 mm wide, baseline y = 77 -->
  ${wordmark}
</svg>
`;
  assertSelfContained(svg);
  return svg;
}
