/**
 * Aweborn Card Front — per-world layout (this module IS the front template).
 *
 * Output is a self-contained SVG: no <text>, no font references, no external
 * files (art must be passed as a data URI). Ready to send to a printer.
 *
 * Format : TCG 63 × 88 mm trim, 3 mm bleed (canvas 69 × 94 mm), 1 unit = 1 mm
 * Trim   : x 3–66, y 3–91      Safe: x 6–63, y 6–88
 * Type   : Jost throughout (SIL OFL); numbers/data set monospaced (tabular cells)
 */
import { outline } from "./outline.mjs";
import { qrPath } from "./qr.mjs";

export const C = {
  bg: "#18181b",
  name: "#f4f4f5",
  strong: "#e4e4e7",
  label: "#d4d4d8",
  muted: "#a1a1aa",
  faint: "#71717a",
  hairline: "#3f3f46",
  divider: "#27272a",
  mark: ["#5b8cb8", "#a480b8", "#e8c860"], // f1 favicon palette, same as the back
  qrBg: "#f4f4f5",
  qrInk: "#18181b",
};

/** Permanent public card URL (Card Invariant: never change this format). */
export function worldUrl(id, arrival) {
  return `https://aweborn.org/w/${id}${arrival === "in" ? "?a=in" : ""}`;
}

/**
 * @param {object} w
 * @param {string} w.id          world UUIDv4
 * @param {string} w.name
 * @param {string} w.creator
 * @param {string} w.coords      e.g. "(1204, -88, 3310)"
 * @param {string} w.sector      e.g. "4:-1:12"
 * @param {string} w.setName     e.g. "ORIGIN SET"
 * @param {string} [w.setNumber] e.g. "01 / 12" (padded to the set's width); omit/empty for single-card sets
 * @param {"orbit"|"in"} [w.arrival]
 * @param {string} [w.artHref]  data URI of raster world art, cropped to fill the window
 * @param {string} [w.artSvg]   OR vector art: SVG markup in a 55 × 45 coordinate space
 * @param {object} [opts]
 * @param {"jost"|"jetbrains"} [opts.numbers]  typeface for data lines (default: monospaced Jost)
 * @returns {{ svg: string, url: string, qr: { modules: number, moduleSize: number, version: number } }}
 */
export function renderFront(w, { numbers = "jost" } = {}) {
  const data = numbers === "jetbrains" ? { font: "mono", wght: 400 } : { font: "jost", wght: 400, mono: true };
  if (!w.artSvg && !w.artHref?.startsWith("data:")) {
    throw new Error("Provide artSvg, or artHref as a data: URI (self-contained SVG)");
  }
  const art = w.artSvg
    ? `<svg x="7" y="15" width="55" height="45" viewBox="0 0 55 45" preserveAspectRatio="xMidYMid slice">${w.artSvg}</svg>`
    : `<image x="7" y="15" width="55" height="45" preserveAspectRatio="xMidYMid slice" href="${w.artHref}" xlink:href="${w.artHref}"/>`;
  const url = worldUrl(w.id, w.arrival);

  // Header: set number (right) first, so the name can shrink to fit beside it.
  const setNo = outline(w.setNumber ?? "", { ...data, size: 2.2, x: 61.5, y: 12.2, anchor: "end", fill: C.faint });
  const name = outline(w.name, {
    font: "jost", wght: 500, size: 4.4, x: 7.5, y: 12.2, fill: C.name,
    maxWidth: 61.5 - setNo.width - 7.5 - 2.5,
  });

  // Creator line: "by " muted + creator emphasized
  const by = outline("by ", { font: "jost", wght: 400, size: 2.7, x: 7.5, y: 65.6, fill: C.muted });
  const creator = outline(w.creator, {
    font: "jost", wght: 500, size: 2.7, x: 7.5 + by.width, y: 65.6, fill: C.strong, maxWidth: 54 - by.width,
  });
  const loc = outline(`${w.coords} · SECTOR ${w.sector}`, {
    ...data, size: 2.1, x: 7.5, y: 70, fill: C.faint, maxWidth: 54,
  });

  // Footer
  const setName = outline(w.setName.toUpperCase(), {
    font: "jost", wght: 500, size: 2.3, tracking: 0.18, x: 14.6, y: 80, fill: C.label, maxWidth: 34,
  });
  const hint = outline("Tap or scan · aweborn.org", {
    font: "jost", wght: 400, size: 2.0, x: 14.6, y: 83.4, fill: C.faint, maxWidth: 34,
  });

  // QR fallback: 10 mm symbol inside a 12 mm light tile (1 mm quiet zone)
  const qr = qrPath(url, { x: 51, y: 76, size: 10, ecc: "M", fill: C.qrInk });

  const svg = `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="69mm" height="94mm" viewBox="0 0 69 94">
  <!--
    Aweborn Card Front — ${escapeXml(w.name)}
    URL: ${url}
    GENERATED by scripts/cards/lib/front.mjs — self-contained (outlined text, embedded art).
    QR: version ${qr.version}, ${qr.modules}×${qr.modules} modules, ${qr.moduleSize.toFixed(3)} mm/module, ECC M
  -->
  <defs>
    <clipPath id="art-window"><rect x="7" y="15" width="55" height="45" rx="1.5"/></clipPath>
    <linearGradient id="art-fade" x1="0" y1="0" x2="0" y2="1">
      <stop offset="70%" stop-color="${C.bg}" stop-opacity="0"/>
      <stop offset="100%" stop-color="${C.bg}" stop-opacity="0.55"/>
    </linearGradient>
  </defs>

  <!-- Full-bleed background -->
  <rect width="69" height="94" fill="${C.bg}"/>

  <!-- Header -->
  ${name.svg}
  ${setNo.svg}

  <!-- Art window (55 × 45 mm, cropped to fill) -->
  <g clip-path="url(#art-window)">
    <rect x="7" y="15" width="55" height="45" fill="#0a0a12"/>
    ${art}
    <rect x="7" y="15" width="55" height="45" fill="url(#art-fade)"/>
  </g>
  <rect x="7" y="15" width="55" height="45" rx="1.5" fill="none" stroke="${C.hairline}" stroke-width="0.25"/>

  <!-- Creator + location -->
  ${by.svg}
  ${creator.svg}
  ${loc.svg}

  <line x1="7" y1="73.5" x2="62" y2="73.5" stroke="${C.divider}" stroke-width="0.2"/>

  <!-- Footer: mark + set name + tap hint -->
  <g transform="translate(9.8 80.6) scale(0.034) translate(-201.5 -198)">
    <circle cx="177" cy="198" r="55" fill="${C.mark[0]}"/>
    <circle cx="247" cy="217" r="34" fill="${C.mark[1]}"/>
    <circle cx="234" cy="173" r="21" fill="${C.mark[2]}"/>
  </g>
  ${setName.svg}
  ${hint.svg}

  <!-- QR fallback → ${url} -->
  <rect x="50" y="75" width="12" height="12" rx="0.8" fill="${C.qrBg}"/>
  ${qr.svg}
</svg>
`;
  assertSelfContained(svg);
  return { svg, url, qr: { modules: qr.modules, moduleSize: qr.moduleSize, version: qr.version } };
}

function escapeXml(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/--/g, "‐‐");
}

/** Throw if the SVG depends on fonts or external files. */
export function assertSelfContained(svg) {
  const problems = [];
  if (/<text[\s>]/.test(svg)) problems.push("<text> element");
  if (/font-family/.test(svg)) problems.push("font-family reference");
  if (/@font-face|@import/.test(svg)) problems.push("CSS font import");
  for (const [, href] of svg.matchAll(/href="([^"]*)"/g)) {
    if (!href.startsWith("data:") && !href.startsWith("#")) problems.push(`external href: ${href.slice(0, 60)}`);
  }
  if (problems.length) throw new Error(`SVG is not self-contained: ${problems.join(", ")}`);
}
